language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
script:
  - yarn docs:build # npm run docs:build
  - echo 'ui.fullstackjavascript.cn' > CNAME
env:
  - GITHUB_TOKEN=9fe592d769d8209ace215577e26e5e188fc23bc9
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master